[2024-10-29 16-13-33] 404 - commande non existante :: /  @  http://localhost:8000/ 
[2024-10-29 16-35-51] 500 - le contrôleur App\Controller\PostsController n'existe pas  @  http://localhost:8000/api/v1/fake-datas/posts 
[2024-10-29 17-43-53] 404 - erreur dans le processus de traitement du routage  @  http://localhost:8000/api/v1/fake-datas/posts 
[2024-10-29 17-45-34] 404 - erreur dans le processus de traitement du routage  @  http://localhost:8000/api/v1/fake-datas/posts 
[2024-10-29 17-47-27] 404 - erreur dans le processus de traitement du routage  @  http://localhost:8000/api/v1/fake-datas/posts 
[2024-10-29 17-47-27] 404 - erreur dans le processus de traitement du routage  @  http://localhost:8000/api/v1/fake-datas/posts 
[2024-10-29 17-47-28] 404 - erreur dans le processus de traitement du routage  @  http://localhost:8000/api/v1/fake-datas/posts 
[2024-10-29 17-47-28] 404 - erreur dans le processus de traitement du routage  @  http://localhost:8000/api/v1/fake-datas/posts 
[2024-10-29 17-47-38] 404 - erreur dans le processus de traitement du routage  @  http://localhost:8000/api/v1/fake-datas/posts 
[2024-10-29 17-50-32] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[HY000]: General error: 26 file is not a database in C:\xampp\htdocs\Mapi\src\Model\Model.php:224 Stack trace: #0 C:\xampp\htdocs\Mapi\src\Model\Model.php(224): PDO->query('SELECT * FROM `...') #1 C:\xampp\htdocs\Mapi\src\Model\Model.php(79): App\Model\Model->query('SELECT * FROM `...') #2 C:\xampp\htdocs\Mapi\src\Controller\PostController.php(13): App\Model\Model->findAll() #3 C:\xampp\htdocs\Mapi\src\bootstrap.php(94): App\Controller\PostController->index() #4 C:\xampp\htdocs\Mapi\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/api/v1/fake-datas/posts 
[2024-10-29 18-03-45] 500 - la méthode show n'existe pas  @  http://localhost:8000/api/v1/fake-datas/posts/123 
[2024-10-29 20-19-05] 405 - méthode incorrecte :: Array  @  http://localhost:8000/api/v1/fake-datas/posts?id=209 
[2024-10-29 20-19-07] 405 - méthode incorrecte :: Array  @  http://localhost:8000/api/v1/fake-datas/posts?id=209 
[2024-10-29 20-19-26] 405 - méthode incorrecte :: Array  @  http://localhost:8000/api/v1/fake-datas/posts?id=209 
[2024-10-29 20-19-28] 405 - méthode incorrecte :: Array  @  http://localhost:8000/api/v1/fake-datas/posts?id=209 
[2024-10-29 20-19-32] 405 - méthode incorrecte :: Array  @  http://localhost:8000/api/v1/fake-datas/posts 
[2024-10-29 20-19-52] 405 - méthode incorrecte :: Array  @  http://localhost:8000/api/v1/fake-datas/posts 
[2024-10-29 20-20-27] 405 - méthode incorrecte :: Array  @  http://localhost:8000/api/v1/fake-datas/posts 
[2024-10-29 20-20-27] 405 - méthode incorrecte :: Array  @  http://localhost:8000/api/v1/fake-datas/posts 
[2024-10-29 20-20-28] 405 - méthode incorrecte :: Array  @  http://localhost:8000/api/v1/fake-datas/posts 
[2024-10-29 20-20-50] 405 - méthode incorrecte :: Array  @  http://localhost:8000/api/v1/fake-datas/posts 
[2024-11-11 15-12-46] 500 - le contrôleur App\Controller\PostController n'existe pas  @  http://localhost:8800/api/v1/fake-datas/posts/1 
[2024-11-12 15-53-55] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'title' in 'field list' in C:\xampp\htdocs\Mapi\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\Mapi\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\Mapi\src\Model\Model.php(157): App\Model\Model->query('INSERT INTO `ow...', Array) #2 C:\xampp\htdocs\Mapi\src\Controller\OwnerController.php(35): App\Model\Model->create(Array) #3 C:\xampp\htdocs\Mapi\src\bootstrap.php(100): App\Controller\OwnerController->create() #4 C:\xampp\htdocs\Mapi\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8800/api/v1/gbox/owner 
[2024-11-12 15-55-58] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'title' in 'field list' in C:\xampp\htdocs\Mapi\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\Mapi\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\Mapi\src\Model\Model.php(157): App\Model\Model->query('INSERT INTO `ow...', Array) #2 C:\xampp\htdocs\Mapi\src\Controller\OwnerController.php(35): App\Model\Model->create(Array) #3 C:\xampp\htdocs\Mapi\src\bootstrap.php(100): App\Controller\OwnerController->create() #4 C:\xampp\htdocs\Mapi\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8800/api/v1/gbox/owner 
[2024-11-13 22-05-29] 500 - la méthode findByTitle n'existe pas  @  http://localhost:8800/api/v1/gbox/games/Minecraft 
[2024-11-13 22-05-47] 500 - la méthode findByTitle n'existe pas  @  http://localhost:8800/api/v1/gbox/games/Minecraft 
[2024-11-13 22-05-48] 500 - la méthode findByTitle n'existe pas  @  http://localhost:8800/api/v1/gbox/games/Minecraft 
[2024-11-13 22-06-34] 500 - la méthode search n'existe pas  @  http://localhost:8800/api/v1/gbox/games/Minecraft 
[2024-11-13 22-07-17] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[HY093]: Invalid parameter number: parameter was not defined in C:\xampp\htdocs\Mapi\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\Mapi\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\Mapi\src\Model\Game.php(23): App\Model\Model->query('SELECT * FROM `...', Array) #2 C:\xampp\htdocs\Mapi\src\Controller\GameController.php(20): App\Model\Game->findByTitle('Minecraft') #3 C:\xampp\htdocs\Mapi\src\bootstrap.php(100): App\Controller\GameController->show('Minecraft') #4 C:\xampp\htdocs\Mapi\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8800/api/v1/gbox/games/Minecraft 
[2024-11-13 22-08-13] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[HY093]: Invalid parameter number: parameter was not defined in C:\xampp\htdocs\Mapi\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\Mapi\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\Mapi\src\Model\Game.php(23): App\Model\Model->query('SELECT * FROM `...', Array) #2 C:\xampp\htdocs\Mapi\src\Controller\GameController.php(20): App\Model\Game->findByTitle('Minecraft') #3 C:\xampp\htdocs\Mapi\src\bootstrap.php(100): App\Controller\GameController->show('Minecraft') #4 C:\xampp\htdocs\Mapi\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8800/api/v1/gbox/games/Minecraft 
[2024-11-13 22-08-56] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[HY093]: Invalid parameter number: parameter was not defined in C:\xampp\htdocs\Mapi\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\Mapi\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\Mapi\src\Model\Game.php(23): App\Model\Model->query('SELECT * FROM `...', Array) #2 C:\xampp\htdocs\Mapi\src\Controller\GameController.php(19): App\Model\Game->findByTitle('Minecraft') #3 C:\xampp\htdocs\Mapi\src\bootstrap.php(100): App\Controller\GameController->show('Minecraft') #4 C:\xampp\htdocs\Mapi\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8800/api/v1/gbox/games/Minecraft 
[2024-11-13 22-08-56] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[HY093]: Invalid parameter number: parameter was not defined in C:\xampp\htdocs\Mapi\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\Mapi\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\Mapi\src\Model\Game.php(23): App\Model\Model->query('SELECT * FROM `...', Array) #2 C:\xampp\htdocs\Mapi\src\Controller\GameController.php(19): App\Model\Game->findByTitle('Minecraft') #3 C:\xampp\htdocs\Mapi\src\bootstrap.php(100): App\Controller\GameController->show('Minecraft') #4 C:\xampp\htdocs\Mapi\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8800/api/v1/gbox/games/Minecraft 
[2024-11-13 22-09-50] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[HY093]: Invalid parameter number: parameter was not defined in C:\xampp\htdocs\Mapi\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\Mapi\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\Mapi\src\Model\Game.php(24): App\Model\Model->query('SELECT * FROM `...', Array) #2 C:\xampp\htdocs\Mapi\src\Controller\GameController.php(19): App\Model\Game->findByTitle('Minecraft') #3 C:\xampp\htdocs\Mapi\src\bootstrap.php(100): App\Controller\GameController->show('Minecraft') #4 C:\xampp\htdocs\Mapi\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8800/api/v1/gbox/games/Minecraft 
[2024-11-19 15-27-45] 500 - le contrôleur App\Controller\AdminController n'existe pas  @  http://localhost:8000/v1/reigns/admin 
[2024-11-19 15-31-38] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mdubois_api_reigns.admin' doesn't exist in C:\xampp\htdocs\apiReigns\src\Model\Model.php:224 Stack trace: #0 C:\xampp\htdocs\apiReigns\src\Model\Model.php(224): PDO->query('SELECT * FROM `...') #1 C:\xampp\htdocs\apiReigns\src\Model\Model.php(79): App\Model\Model->query('SELECT * FROM `...') #2 C:\xampp\htdocs\apiReigns\src\Controller\AdminController.php(13): App\Model\Model->findAll() #3 C:\xampp\htdocs\apiReigns\src\bootstrap.php(98): App\Controller\AdminController->index() #4 C:\xampp\htdocs\apiReigns\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/admin 
[2024-11-19 15-32-20] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mdubois_api_reigns.admin' doesn't exist in C:\xampp\htdocs\apiReigns\src\Model\Model.php:224 Stack trace: #0 C:\xampp\htdocs\apiReigns\src\Model\Model.php(224): PDO->query('SELECT * FROM `...') #1 C:\xampp\htdocs\apiReigns\src\Model\Model.php(79): App\Model\Model->query('SELECT * FROM `...') #2 C:\xampp\htdocs\apiReigns\src\Controller\AdminController.php(13): App\Model\Model->findAll() #3 C:\xampp\htdocs\apiReigns\src\bootstrap.php(98): App\Controller\AdminController->index() #4 C:\xampp\htdocs\apiReigns\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/admin 
[2024-11-19 15-32-21] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mdubois_api_reigns.admin' doesn't exist in C:\xampp\htdocs\apiReigns\src\Model\Model.php:224 Stack trace: #0 C:\xampp\htdocs\apiReigns\src\Model\Model.php(224): PDO->query('SELECT * FROM `...') #1 C:\xampp\htdocs\apiReigns\src\Model\Model.php(79): App\Model\Model->query('SELECT * FROM `...') #2 C:\xampp\htdocs\apiReigns\src\Controller\AdminController.php(13): App\Model\Model->findAll() #3 C:\xampp\htdocs\apiReigns\src\bootstrap.php(98): App\Controller\AdminController->index() #4 C:\xampp\htdocs\apiReigns\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/admin 
[2024-11-19 15-33-19] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mdubois_api_reigns.admin' doesn't exist in C:\xampp\htdocs\apiReigns\src\Model\Model.php:224 Stack trace: #0 C:\xampp\htdocs\apiReigns\src\Model\Model.php(224): PDO->query('SELECT * FROM `...') #1 C:\xampp\htdocs\apiReigns\src\Model\Model.php(79): App\Model\Model->query('SELECT * FROM `...') #2 C:\xampp\htdocs\apiReigns\src\Controller\AdminController.php(14): App\Model\Model->findAll() #3 C:\xampp\htdocs\apiReigns\src\bootstrap.php(98): App\Controller\AdminController->index() #4 C:\xampp\htdocs\apiReigns\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/admin 
[2024-11-19 17-03-19] 500 - la méthode getByMail n'existe pas  @  http://localhost:8000/v1/reigns/administrateur/mail 
[2024-11-19 17-03-20] 500 - la méthode getByMail n'existe pas  @  http://localhost:8000/v1/reigns/administrateur/mail 
[2024-11-19 18-18-48] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' in C:\xampp\htdocs\apiReigns\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns\src\Model\Model.php(186): App\Model\Model->query('UPDATE `createu...', Array) #2 C:\xampp\htdocs\apiReigns\src\Controller\CreateurController.php(88): App\Model\Model->update(22, Array) #3 C:\xampp\htdocs\apiReigns\src\bootstrap.php(98): App\Controller\CreateurController->edit() #4 C:\xampp\htdocs\apiReigns\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/createur 
[2024-11-19 18-20-21] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' in C:\xampp\htdocs\apiReigns\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns\src\Model\Model.php(186): App\Model\Model->query('UPDATE `createu...', Array) #2 C:\xampp\htdocs\apiReigns\src\Controller\CreateurController.php(88): App\Model\Model->update(22, Array) #3 C:\xampp\htdocs\apiReigns\src\bootstrap.php(98): App\Controller\CreateurController->edit() #4 C:\xampp\htdocs\apiReigns\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/createur 
[2024-11-19 18-20-57] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' in C:\xampp\htdocs\apiReigns\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns\src\Model\Model.php(186): App\Model\Model->query('UPDATE `createu...', Array) #2 C:\xampp\htdocs\apiReigns\src\Controller\CreateurController.php(89): App\Model\Model->update(22, Array) #3 C:\xampp\htdocs\apiReigns\src\bootstrap.php(98): App\Controller\CreateurController->edit() #4 C:\xampp\htdocs\apiReigns\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/createur 
[2024-11-19 18-25-24] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' in C:\xampp\htdocs\apiReigns\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns\src\Model\Model.php(186): App\Model\Model->query('UPDATE `createu...', Array) #2 C:\xampp\htdocs\apiReigns\src\Controller\CreateurController.php(89): App\Model\Model->update(22, Array) #3 C:\xampp\htdocs\apiReigns\src\bootstrap.php(98): App\Controller\CreateurController->edit() #4 C:\xampp\htdocs\apiReigns\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/createur 
[2024-11-19 18-32-11] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' in C:\xampp\htdocs\apiReigns\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns\src\Model\Model.php(186): App\Model\Model->query('UPDATE `createu...', Array) #2 C:\xampp\htdocs\apiReigns\src\Controller\CreateurController.php(88): App\Model\Model->update(22, Array) #3 C:\xampp\htdocs\apiReigns\src\bootstrap.php(98): App\Controller\CreateurController->edit() #4 C:\xampp\htdocs\apiReigns\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/createur 
[2024-11-19 18-32-11] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' in C:\xampp\htdocs\apiReigns\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns\src\Model\Model.php(186): App\Model\Model->query('UPDATE `createu...', Array) #2 C:\xampp\htdocs\apiReigns\src\Controller\CreateurController.php(88): App\Model\Model->update(22, Array) #3 C:\xampp\htdocs\apiReigns\src\bootstrap.php(98): App\Controller\CreateurController->edit() #4 C:\xampp\htdocs\apiReigns\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/createur 
[2024-11-19 18-37-13] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' in C:\xampp\htdocs\apiReigns\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns\src\Model\Model.php(186): App\Model\Model->query('UPDATE `createu...', Array) #2 C:\xampp\htdocs\apiReigns\src\Controller\CreateurController.php(88): App\Model\Model->update(22, Array) #3 C:\xampp\htdocs\apiReigns\src\bootstrap.php(98): App\Controller\CreateurController->edit() #4 C:\xampp\htdocs\apiReigns\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/createur 
[2024-11-19 18-40-22] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' in C:\xampp\htdocs\apiReigns\src\Model\Model.php:221 Stack trace: #0 C:\xampp\htdocs\apiReigns\src\Model\Model.php(221): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns\src\Model\Model.php(187): App\Model\Model->query('UPDATE `createu...', Array) #2 C:\xampp\htdocs\apiReigns\src\Controller\CreateurController.php(88): App\Model\Model->update(22, Array) #3 C:\xampp\htdocs\apiReigns\src\bootstrap.php(98): App\Controller\CreateurController->edit() #4 C:\xampp\htdocs\apiReigns\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/createur 
[2024-11-19 18-40-46] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' in C:\xampp\htdocs\apiReigns\src\Model\Model.php:221 Stack trace: #0 C:\xampp\htdocs\apiReigns\src\Model\Model.php(221): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns\src\Model\Model.php(187): App\Model\Model->query('UPDATE `createu...', Array) #2 C:\xampp\htdocs\apiReigns\src\Controller\CreateurController.php(88): App\Model\Model->update(22, Array) #3 C:\xampp\htdocs\apiReigns\src\bootstrap.php(98): App\Controller\CreateurController->edit() #4 C:\xampp\htdocs\apiReigns\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/createur 
[2024-11-19 18-40-48] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' in C:\xampp\htdocs\apiReigns\src\Model\Model.php:221 Stack trace: #0 C:\xampp\htdocs\apiReigns\src\Model\Model.php(221): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns\src\Model\Model.php(187): App\Model\Model->query('UPDATE `createu...', Array) #2 C:\xampp\htdocs\apiReigns\src\Controller\CreateurController.php(88): App\Model\Model->update(22, Array) #3 C:\xampp\htdocs\apiReigns\src\bootstrap.php(98): App\Controller\CreateurController->edit() #4 C:\xampp\htdocs\apiReigns\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/createur 
[2024-11-19 18-41-00] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' in C:\xampp\htdocs\apiReigns\src\Model\Model.php:221 Stack trace: #0 C:\xampp\htdocs\apiReigns\src\Model\Model.php(221): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns\src\Model\Model.php(187): App\Model\Model->query('UPDATE `createu...', Array) #2 C:\xampp\htdocs\apiReigns\src\Controller\CreateurController.php(88): App\Model\Model->update(22, Array) #3 C:\xampp\htdocs\apiReigns\src\bootstrap.php(98): App\Controller\CreateurController->edit() #4 C:\xampp\htdocs\apiReigns\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/createur 
[2024-11-19 18-41-01] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' in C:\xampp\htdocs\apiReigns\src\Model\Model.php:221 Stack trace: #0 C:\xampp\htdocs\apiReigns\src\Model\Model.php(221): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns\src\Model\Model.php(187): App\Model\Model->query('UPDATE `createu...', Array) #2 C:\xampp\htdocs\apiReigns\src\Controller\CreateurController.php(88): App\Model\Model->update(22, Array) #3 C:\xampp\htdocs\apiReigns\src\bootstrap.php(98): App\Controller\CreateurController->edit() #4 C:\xampp\htdocs\apiReigns\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/createur 
[2024-11-19 18-50-44] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' in C:\xampp\htdocs\apiReigns\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns\src\Model\Model.php(187): App\Model\Model->query('UPDATE `createu...', Array) #2 C:\xampp\htdocs\apiReigns\src\Controller\CreateurController.php(88): App\Model\Model->update(22, Array) #3 C:\xampp\htdocs\apiReigns\src\bootstrap.php(98): App\Controller\CreateurController->edit() #4 C:\xampp\htdocs\apiReigns\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/createur 
[2024-11-19 18-50-45] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' in C:\xampp\htdocs\apiReigns\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns\src\Model\Model.php(187): App\Model\Model->query('UPDATE `createu...', Array) #2 C:\xampp\htdocs\apiReigns\src\Controller\CreateurController.php(88): App\Model\Model->update(22, Array) #3 C:\xampp\htdocs\apiReigns\src\bootstrap.php(98): App\Controller\CreateurController->edit() #4 C:\xampp\htdocs\apiReigns\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/createur 
[2024-11-19 18-50-46] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' in C:\xampp\htdocs\apiReigns\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns\src\Model\Model.php(187): App\Model\Model->query('UPDATE `createu...', Array) #2 C:\xampp\htdocs\apiReigns\src\Controller\CreateurController.php(88): App\Model\Model->update(22, Array) #3 C:\xampp\htdocs\apiReigns\src\bootstrap.php(98): App\Controller\CreateurController->edit() #4 C:\xampp\htdocs\apiReigns\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/createur 
[2024-11-19 18-50-47] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' in C:\xampp\htdocs\apiReigns\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns\src\Model\Model.php(187): App\Model\Model->query('UPDATE `createu...', Array) #2 C:\xampp\htdocs\apiReigns\src\Controller\CreateurController.php(88): App\Model\Model->update(22, Array) #3 C:\xampp\htdocs\apiReigns\src\bootstrap.php(98): App\Controller\CreateurController->edit() #4 C:\xampp\htdocs\apiReigns\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/createur 
[2024-11-19 18-50-48] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' in C:\xampp\htdocs\apiReigns\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns\src\Model\Model.php(187): App\Model\Model->query('UPDATE `createu...', Array) #2 C:\xampp\htdocs\apiReigns\src\Controller\CreateurController.php(88): App\Model\Model->update(22, Array) #3 C:\xampp\htdocs\apiReigns\src\bootstrap.php(98): App\Controller\CreateurController->edit() #4 C:\xampp\htdocs\apiReigns\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/createur 
[2024-11-19 18-50-48] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' in C:\xampp\htdocs\apiReigns\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns\src\Model\Model.php(187): App\Model\Model->query('UPDATE `createu...', Array) #2 C:\xampp\htdocs\apiReigns\src\Controller\CreateurController.php(88): App\Model\Model->update(22, Array) #3 C:\xampp\htdocs\apiReigns\src\bootstrap.php(98): App\Controller\CreateurController->edit() #4 C:\xampp\htdocs\apiReigns\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/createur 
[2024-11-19 18-50-49] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' in C:\xampp\htdocs\apiReigns\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns\src\Model\Model.php(187): App\Model\Model->query('UPDATE `createu...', Array) #2 C:\xampp\htdocs\apiReigns\src\Controller\CreateurController.php(88): App\Model\Model->update(22, Array) #3 C:\xampp\htdocs\apiReigns\src\bootstrap.php(98): App\Controller\CreateurController->edit() #4 C:\xampp\htdocs\apiReigns\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/createur 
[2024-11-19 18-50-49] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' in C:\xampp\htdocs\apiReigns\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns\src\Model\Model.php(187): App\Model\Model->query('UPDATE `createu...', Array) #2 C:\xampp\htdocs\apiReigns\src\Controller\CreateurController.php(88): App\Model\Model->update(22, Array) #3 C:\xampp\htdocs\apiReigns\src\bootstrap.php(98): App\Controller\CreateurController->edit() #4 C:\xampp\htdocs\apiReigns\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/createur 
[2024-11-19 18-50-49] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' in C:\xampp\htdocs\apiReigns\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns\src\Model\Model.php(187): App\Model\Model->query('UPDATE `createu...', Array) #2 C:\xampp\htdocs\apiReigns\src\Controller\CreateurController.php(88): App\Model\Model->update(22, Array) #3 C:\xampp\htdocs\apiReigns\src\bootstrap.php(98): App\Controller\CreateurController->edit() #4 C:\xampp\htdocs\apiReigns\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/createur 
[2024-11-19 18-52-41] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' in C:\xampp\htdocs\apiReigns\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns\src\Model\Model.php(187): App\Model\Model->query('UPDATE `createu...', Array) #2 C:\xampp\htdocs\apiReigns\src\Controller\CreateurController.php(88): App\Model\Model->update(22, Array) #3 C:\xampp\htdocs\apiReigns\src\bootstrap.php(98): App\Controller\CreateurController->edit() #4 C:\xampp\htdocs\apiReigns\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/createur 
[2024-11-19 18-52-42] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' in C:\xampp\htdocs\apiReigns\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns\src\Model\Model.php(187): App\Model\Model->query('UPDATE `createu...', Array) #2 C:\xampp\htdocs\apiReigns\src\Controller\CreateurController.php(88): App\Model\Model->update(22, Array) #3 C:\xampp\htdocs\apiReigns\src\bootstrap.php(98): App\Controller\CreateurController->edit() #4 C:\xampp\htdocs\apiReigns\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/createur 
[2024-11-19 18-52-43] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' in C:\xampp\htdocs\apiReigns\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns\src\Model\Model.php(187): App\Model\Model->query('UPDATE `createu...', Array) #2 C:\xampp\htdocs\apiReigns\src\Controller\CreateurController.php(88): App\Model\Model->update(22, Array) #3 C:\xampp\htdocs\apiReigns\src\bootstrap.php(98): App\Controller\CreateurController->edit() #4 C:\xampp\htdocs\apiReigns\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/createur 
[2024-11-19 18-52-44] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' in C:\xampp\htdocs\apiReigns\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns\src\Model\Model.php(187): App\Model\Model->query('UPDATE `createu...', Array) #2 C:\xampp\htdocs\apiReigns\src\Controller\CreateurController.php(88): App\Model\Model->update(22, Array) #3 C:\xampp\htdocs\apiReigns\src\bootstrap.php(98): App\Controller\CreateurController->edit() #4 C:\xampp\htdocs\apiReigns\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/createur 
[2024-11-19 18-52-45] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' in C:\xampp\htdocs\apiReigns\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns\src\Model\Model.php(187): App\Model\Model->query('UPDATE `createu...', Array) #2 C:\xampp\htdocs\apiReigns\src\Controller\CreateurController.php(88): App\Model\Model->update(22, Array) #3 C:\xampp\htdocs\apiReigns\src\bootstrap.php(98): App\Controller\CreateurController->edit() #4 C:\xampp\htdocs\apiReigns\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/createur 
[2024-11-19 18-52-46] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' in C:\xampp\htdocs\apiReigns\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns\src\Model\Model.php(187): App\Model\Model->query('UPDATE `createu...', Array) #2 C:\xampp\htdocs\apiReigns\src\Controller\CreateurController.php(88): App\Model\Model->update(22, Array) #3 C:\xampp\htdocs\apiReigns\src\bootstrap.php(98): App\Controller\CreateurController->edit() #4 C:\xampp\htdocs\apiReigns\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/createur 
[2024-11-20 22-15-37] 500 - le contrôleur App\Controller\CarteController n'existe pas  @  http://localhost:8000/v1/reigns/carte 
[2024-11-20 22-55-29] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`mdubois_api_reigns`.`carte`, CONSTRAINT `carte_ibfk_1` FOREIGN KEY (`id_createur`) REFERENCES `createur` (`id_createur`)) in C:\xampp\htdocs\apiReigns\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns\src\Model\Model.php(157): App\Model\Model->query('INSERT INTO `ca...', Array) #2 C:\xampp\htdocs\apiReigns\src\Controller\CarteController.php(56): App\Model\Model->create(Array) #3 C:\xampp\htdocs\apiReigns\src\bootstrap.php(98): App\Controller\CarteController->add() #4 C:\xampp\htdocs\apiReigns\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/carte 
[2024-11-20 22-58-18] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`mdubois_api_reigns`.`carte`, CONSTRAINT `carte_ibfk_1` FOREIGN KEY (`id_createur`) REFERENCES `createur` (`id_createur`)) in C:\xampp\htdocs\apiReigns\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns\src\Model\Model.php(157): App\Model\Model->query('INSERT INTO `ca...', Array) #2 C:\xampp\htdocs\apiReigns\src\Controller\CarteController.php(56): App\Model\Model->create(Array) #3 C:\xampp\htdocs\apiReigns\src\bootstrap.php(98): App\Controller\CarteController->add() #4 C:\xampp\htdocs\apiReigns\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/carte 
[2024-11-20 22-58-51] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`mdubois_api_reigns`.`carte`, CONSTRAINT `carte_ibfk_1` FOREIGN KEY (`id_createur`) REFERENCES `createur` (`id_createur`)) in C:\xampp\htdocs\apiReigns\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns\src\Model\Model.php(157): App\Model\Model->query('INSERT INTO `ca...', Array) #2 C:\xampp\htdocs\apiReigns\src\Controller\CarteController.php(57): App\Model\Model->create(Array) #3 C:\xampp\htdocs\apiReigns\src\bootstrap.php(98): App\Controller\CarteController->add() #4 C:\xampp\htdocs\apiReigns\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/carte 
[2024-11-20 23-06-09] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`mdubois_api_reigns`.`carte`, CONSTRAINT `carte_ibfk_1` FOREIGN KEY (`id_createur`) REFERENCES `createur` (`id_createur`)) in C:\xampp\htdocs\apiReigns\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns\src\Model\Model.php(157): App\Model\Model->query('INSERT INTO `ca...', Array) #2 C:\xampp\htdocs\apiReigns\src\Controller\CarteController.php(57): App\Model\Model->create(Array) #3 C:\xampp\htdocs\apiReigns\src\bootstrap.php(98): App\Controller\CarteController->add() #4 C:\xampp\htdocs\apiReigns\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/carte 
[2024-11-20 23-15-31] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`mdubois_api_reigns`.`carte`, CONSTRAINT `carte_ibfk_1` FOREIGN KEY (`id_createur`) REFERENCES `createur` (`id_createur`)) in C:\xampp\htdocs\apiReigns\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns\src\Model\Model.php(157): App\Model\Model->query('INSERT INTO `ca...', Array) #2 C:\xampp\htdocs\apiReigns\src\Controller\CarteController.php(57): App\Model\Model->create(Array) #3 C:\xampp\htdocs\apiReigns\src\bootstrap.php(98): App\Controller\CarteController->add() #4 C:\xampp\htdocs\apiReigns\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/carte 
[2024-11-20 23-51-39] 500 - le contrôleur App\Controller\CarteAleaController n'existe pas  @  http://localhost:8000/v1/reigns/carteAlea 
[2024-11-20 23-54-22] 500 - le contrôleur App\Controller\CarteAleaController n'existe pas  @  http://localhost:8000/v1/reigns/carteAlea 
[2024-11-21 23-16-11] 405 - méthode incorrecte :: Array  @  http://localhost:8000/v1/reigns/administrateur/check 
[2024-11-27 13-11-23] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' in C:\xampp\htdocs\apiReigns_v3\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns_v3\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns_v3\src\Model\Deck.php(64): App\Model\Model->query('SELECT * FROM `...', Array) #2 C:\xampp\htdocs\apiReigns_v3\src\Controller\DeckController.php(148): App\Model\Deck->getLike(8) #3 C:\xampp\htdocs\apiReigns_v3\src\Controller\DeckController.php(158): App\Controller\DeckController->getLike(8) #4 C:\xampp\htdocs\apiReigns_v3\src\bootstrap.php(98): App\Controller\DeckController->addLike() #5 C:\xampp\htdocs\apiReigns_v3\public\index.php(3): require('C:\\xampp\\htdocs...') #6 {main}  @  http://localhost:8000/v1/reigns/deck/like 
[2024-11-27 13-12-09] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' in C:\xampp\htdocs\apiReigns_v3\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns_v3\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns_v3\src\Model\Deck.php(64): App\Model\Model->query('SELECT * FROM `...', Array) #2 C:\xampp\htdocs\apiReigns_v3\src\Controller\DeckController.php(148): App\Model\Deck->getLike(8) #3 C:\xampp\htdocs\apiReigns_v3\src\Controller\DeckController.php(158): App\Controller\DeckController->getLike(8) #4 C:\xampp\htdocs\apiReigns_v3\src\bootstrap.php(98): App\Controller\DeckController->addLike() #5 C:\xampp\htdocs\apiReigns_v3\public\index.php(3): require('C:\\xampp\\htdocs...') #6 {main}  @  http://localhost:8000/v1/reigns/deck/like 
[2024-11-27 13-12-37] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' in C:\xampp\htdocs\apiReigns_v3\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns_v3\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns_v3\src\Model\Deck.php(64): App\Model\Model->query('SELECT * FROM `...', Array) #2 C:\xampp\htdocs\apiReigns_v3\src\Controller\DeckController.php(148): App\Model\Deck->getLike(8) #3 C:\xampp\htdocs\apiReigns_v3\src\Controller\DeckController.php(158): App\Controller\DeckController->getLike(8) #4 C:\xampp\htdocs\apiReigns_v3\src\bootstrap.php(98): App\Controller\DeckController->addLike() #5 C:\xampp\htdocs\apiReigns_v3\public\index.php(3): require('C:\\xampp\\htdocs...') #6 {main}  @  http://localhost:8000/v1/reigns/deck/like 
[2024-11-27 13-12-50] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' in C:\xampp\htdocs\apiReigns_v3\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns_v3\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns_v3\src\Model\Deck.php(64): App\Model\Model->query('SELECT * FROM `...', Array) #2 C:\xampp\htdocs\apiReigns_v3\src\Controller\DeckController.php(148): App\Model\Deck->getLike(8) #3 C:\xampp\htdocs\apiReigns_v3\src\Controller\DeckController.php(158): App\Controller\DeckController->getLike(8) #4 C:\xampp\htdocs\apiReigns_v3\src\bootstrap.php(98): App\Controller\DeckController->addLike() #5 C:\xampp\htdocs\apiReigns_v3\public\index.php(3): require('C:\\xampp\\htdocs...') #6 {main}  @  http://localhost:8000/v1/reigns/deck/like 
[2024-11-27 13-13-44] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' in C:\xampp\htdocs\apiReigns_v3\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns_v3\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns_v3\src\Model\Deck.php(64): App\Model\Model->query('SELECT * FROM `...', Array) #2 C:\xampp\htdocs\apiReigns_v3\src\Controller\DeckController.php(150): App\Model\Deck->getLike(8) #3 C:\xampp\htdocs\apiReigns_v3\src\bootstrap.php(98): App\Controller\DeckController->addLike() #4 C:\xampp\htdocs\apiReigns_v3\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/deck/like 
[2024-11-27 13-13-45] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' in C:\xampp\htdocs\apiReigns_v3\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns_v3\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns_v3\src\Model\Deck.php(64): App\Model\Model->query('SELECT * FROM `...', Array) #2 C:\xampp\htdocs\apiReigns_v3\src\Controller\DeckController.php(150): App\Model\Deck->getLike(8) #3 C:\xampp\htdocs\apiReigns_v3\src\bootstrap.php(98): App\Controller\DeckController->addLike() #4 C:\xampp\htdocs\apiReigns_v3\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/deck/like 
[2024-11-27 13-14-15] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' in C:\xampp\htdocs\apiReigns_v3\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns_v3\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns_v3\src\Model\Deck.php(64): App\Model\Model->query('SELECT nb_jaime...', Array) #2 C:\xampp\htdocs\apiReigns_v3\src\Controller\DeckController.php(150): App\Model\Deck->getLike(8) #3 C:\xampp\htdocs\apiReigns_v3\src\bootstrap.php(98): App\Controller\DeckController->addLike() #4 C:\xampp\htdocs\apiReigns_v3\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/deck/like 
[2024-11-27 13-14-16] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' in C:\xampp\htdocs\apiReigns_v3\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns_v3\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns_v3\src\Model\Deck.php(64): App\Model\Model->query('SELECT nb_jaime...', Array) #2 C:\xampp\htdocs\apiReigns_v3\src\Controller\DeckController.php(150): App\Model\Deck->getLike(8) #3 C:\xampp\htdocs\apiReigns_v3\src\bootstrap.php(98): App\Controller\DeckController->addLike() #4 C:\xampp\htdocs\apiReigns_v3\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v1/reigns/deck/like 
[2024-11-27 14-35-45] 405 - méthode incorrecte :: Array  @  http://localhost:8000/v3/reigns/deck/valid/minmax 
[2024-11-27 14-36-20] 405 - méthode incorrecte :: Array  @  http://localhost:8000/v3/reigns/deck/valid/minmax 
[2024-11-27 14-36-22] 405 - méthode incorrecte :: Array  @  http://localhost:8000/v3/reigns/deck/valid/minmax 
[2024-11-27 14-36-23] 405 - méthode incorrecte :: Array  @  http://localhost:8000/v3/reigns/deck/valid/minmax 
[2024-11-27 14-36-23] 405 - méthode incorrecte :: Array  @  http://localhost:8000/v3/reigns/deck/valid/minmax 
[2024-11-27 14-36-24] 405 - méthode incorrecte :: Array  @  http://localhost:8000/v3/reigns/deck/valid/minmax 
[2024-12-08 12-24-36] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens in C:\xampp\htdocs\apiReigns_v3\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns_v3\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns_v3\src\Model\Carte.php(52): App\Model\Model->query('SELECT * FROM `...', Array) #2 C:\xampp\htdocs\apiReigns_v3\src\Controller\CarteController.php(132): App\Model\Carte->getAllByIdDeck(12) #3 C:\xampp\htdocs\apiReigns_v3\src\bootstrap.php(98): App\Controller\CarteController->getAllByIdDeck() #4 C:\xampp\htdocs\apiReigns_v3\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v3/reigns/carte/deck/id 
[2024-12-08 12-24-36] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens in C:\xampp\htdocs\apiReigns_v3\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns_v3\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns_v3\src\Model\Carte.php(52): App\Model\Model->query('SELECT * FROM `...', Array) #2 C:\xampp\htdocs\apiReigns_v3\src\Controller\CarteController.php(132): App\Model\Carte->getAllByIdDeck(12) #3 C:\xampp\htdocs\apiReigns_v3\src\bootstrap.php(98): App\Controller\CarteController->getAllByIdDeck() #4 C:\xampp\htdocs\apiReigns_v3\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v3/reigns/carte/deck/id 
[2024-12-08 12-24-37] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens in C:\xampp\htdocs\apiReigns_v3\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns_v3\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns_v3\src\Model\Carte.php(52): App\Model\Model->query('SELECT * FROM `...', Array) #2 C:\xampp\htdocs\apiReigns_v3\src\Controller\CarteController.php(132): App\Model\Carte->getAllByIdDeck(12) #3 C:\xampp\htdocs\apiReigns_v3\src\bootstrap.php(98): App\Controller\CarteController->getAllByIdDeck() #4 C:\xampp\htdocs\apiReigns_v3\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v3/reigns/carte/deck/id 
[2024-12-08 12-24-38] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens in C:\xampp\htdocs\apiReigns_v3\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns_v3\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns_v3\src\Model\Carte.php(52): App\Model\Model->query('SELECT * FROM `...', Array) #2 C:\xampp\htdocs\apiReigns_v3\src\Controller\CarteController.php(132): App\Model\Carte->getAllByIdDeck(12) #3 C:\xampp\htdocs\apiReigns_v3\src\bootstrap.php(98): App\Controller\CarteController->getAllByIdDeck() #4 C:\xampp\htdocs\apiReigns_v3\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v3/reigns/carte/deck/id 
[2024-12-08 12-24-38] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens in C:\xampp\htdocs\apiReigns_v3\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns_v3\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns_v3\src\Model\Carte.php(52): App\Model\Model->query('SELECT * FROM `...', Array) #2 C:\xampp\htdocs\apiReigns_v3\src\Controller\CarteController.php(132): App\Model\Carte->getAllByIdDeck(12) #3 C:\xampp\htdocs\apiReigns_v3\src\bootstrap.php(98): App\Controller\CarteController->getAllByIdDeck() #4 C:\xampp\htdocs\apiReigns_v3\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v3/reigns/carte/deck/id 
[2024-12-08 13-25-08] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[HY093]: Invalid parameter number: parameter was not defined in C:\xampp\htdocs\apiReigns_v3\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns_v3\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns_v3\src\Model\Carte.php(69): App\Model\Model->query('SELECT COUNT(id...', Array) #2 C:\xampp\htdocs\apiReigns_v3\src\Controller\CarteController.php(156): App\Model\Carte->count(12) #3 C:\xampp\htdocs\apiReigns_v3\src\bootstrap.php(98): App\Controller\CarteController->count() #4 C:\xampp\htdocs\apiReigns_v3\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v3/reigns/carte/deck/count 
[2024-12-08 13-25-42] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[HY093]: Invalid parameter number: parameter was not defined in C:\xampp\htdocs\apiReigns_v3\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns_v3\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns_v3\src\Model\Carte.php(69): App\Model\Model->query('SELECT COUNT(id...', Array) #2 C:\xampp\htdocs\apiReigns_v3\src\Controller\CarteController.php(157): App\Model\Carte->count(12) #3 C:\xampp\htdocs\apiReigns_v3\src\bootstrap.php(98): App\Controller\CarteController->count() #4 C:\xampp\htdocs\apiReigns_v3\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v3/reigns/carte/deck/count 
[2024-12-08 13-25-42] 404 - erreur dans le processus de traitement du routagePDOException: SQLSTATE[HY093]: Invalid parameter number: parameter was not defined in C:\xampp\htdocs\apiReigns_v3\src\Model\Model.php:220 Stack trace: #0 C:\xampp\htdocs\apiReigns_v3\src\Model\Model.php(220): PDOStatement->execute(Array) #1 C:\xampp\htdocs\apiReigns_v3\src\Model\Carte.php(69): App\Model\Model->query('SELECT COUNT(id...', Array) #2 C:\xampp\htdocs\apiReigns_v3\src\Controller\CarteController.php(157): App\Model\Carte->count(12) #3 C:\xampp\htdocs\apiReigns_v3\src\bootstrap.php(98): App\Controller\CarteController->count() #4 C:\xampp\htdocs\apiReigns_v3\public\index.php(3): require('C:\\xampp\\htdocs...') #5 {main}  @  http://localhost:8000/v3/reigns/carte/deck/count 
